steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/studious-vector-287619/todo-backend:latest', '-t', 'gcr.io/studious-vector-287619/todo-backend:$SHORT_SHA', '.',
      '--build-arg', 'ALLOWED_CORS=${_ALLOWED_CORS}',
      '--build-arg', 'DATABASE_CONNECTION_STRING=${_DATABASE_CONNECTION_STRING}'
    ]
    env:
      - 'ALLOWED_CORS=$ALLOWED_CORS'
      - 'DATABASE_CONNECTION_STRING=$DATABASE_CONNECTION_STRING'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/studious-vector-287619/todo-backend:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/studious-vector-287619/todo-backend:$SHORT_SHA']
  
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s
    - --image=gcr.io/studious-vector-287619/todo-backend:$SHORT_SHA
    - --location=us-central1-c
    - --cluster=teste-cluster

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: [
  #     'set',
  #     'image',
  #     'deployment',
  #     'teste-todolist-backend',
  #     'teste-todolist-backend=gcr.io/studious-vector-287619/todo-backend:$SHORT_SHA'
  #   ]

    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=teste-cluster'
    