FROM node:14-alpine

# ARG ALLOWED_CORS
# ARG DATABASE_CONNECTION_STRING

# ENV ALLOWED_CORS=${ALLOWED_CORS}
# ENV DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}

WORKDIR /app

COPY ./backend/package*.json ./

RUN npm install --production

COPY ./backend ./

EXPOSE 3001

CMD ["npm", "start"]