apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-todolist-backend
  namespace: todolist-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste-todolist-backend
  template:
    metadata:
      namespace: todolist-staging
      labels:
        app: teste-todolist-backend
    spec:
      containers:
        - name: teste-todolist-backend
          image: gcr.io/studious-vector-287619/todo-backend:latest
          ports:
            - containerPort: 8080