apiVersion: v1
kind: Service
metadata:
  name: todolist-backend-service
  namespace: todolist-staging
  labels:
    app: teste-todolist-backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http-srv
      port: 80
      targetPort: 3001
  selector:
    app: teste-todolist-backend
