/* eslint-disable import/prefer-default-export */
import {
    CropFree,
    Settings,
    Person,
    PermContactCalendar,
    LocalDining,
    Edit,
    Close,
    Backup,
    ErrorOutline,
    CheckCircleOutline,
    ArrowBackIos,
    ArrowForwardIos,
    Facebook,
    Instagram,
    Email,
    Link,
    Reply,
    AttachFile,
    Assignment,
    Add,
    AccessTime,
    FormatListBulleted,
    EmojiEvents,
} from '@material-ui/icons';

export {
    CropFree,
    Settings,
    Person,
    PermContactCalendar,
    LocalDining,
    Edit,
    Close,
    Backup,
    ErrorOutline,
    CheckCircleOutline,
    ArrowBackIos,
    ArrowForwardIos,
    Facebook,
    Instagram,
    Email,
    Link,
    AttachFile,
    Reply,
    Assignment,
    Add,
    AccessTime,
    FormatListBulleted,
    EmojiEvents,
};
